---
development:
  dialect: "sqlite3"
  database: ./db_development.sqlite

test:
  dialect: "sqlite3"
  database: ./db_test.sqlite

production:
  dialect: "sqlite3"
  database: ./db_production.sqlite
